AssosiationDjango/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^', include('post.ru_urls')),
    url(r'^en/', include('post.en_urls')),
    url(r'^mediaportal/', include('media_gallery.ru_urls')),
    url(r'^en/mediaportal/', include('media_gallery.en_urls')),
]

if settings.DEBUG: urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/models.py
# -*- coding: utf-8 -*-
# Create your models here.
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse
from django.utils import timezone
from django.utils.safestring import mark_safe


class Language(models.Model):
    class Meta:
        db_table = u'Тил'
        verbose_name = u'Тил'
        verbose_name_plural = u'Тилдер'
        ordering = [u'-id']

    name = models.CharField(verbose_name=u'Аты', max_length=80, blank=True, null=True, default=None)

    def __str__(self):
        return self.name


class GlavCategory(models.Model):
    class Meta:
        db_table = u'Главная категория'
        verbose_name_plural = u'Главные категории'
        verbose_name = u'Главная категория'
        ordering = ['-id']

    language = models.ForeignKey(Language, verbose_name=u'Тили', on_delete=models.CASCADE)
    name = models.CharField(verbose_name=u'Аты', max_length=150)
    slug = models.CharField(verbose_name=u'Транслит', max_length=200, blank=True)
    style = models.CharField(verbose_name=u'Добавить класс', max_length=200, blank=True, null=True)

    def __unicode__(self):
        return self.name


class Category(models.Model):
    class Meta:
        db_table = u'Category'
        verbose_name = u'Категория'
        verbose_name_plural = u'Категориялар'
        ordering = [u'-id']

    language = models.ForeignKey(Language, verbose_name=u'Тили', on_delete=models.CASCADE)
    glavcategory = models.ForeignKey(GlavCategory, verbose_name=u'Главная категория', on_delete=models.CASCADE)
    name = models.CharField(verbose_name=u'Аты', max_length=80, blank=True, null=True, default=None)
    slug = models.CharField(verbose_name=u'Транслит', max_length=200, blank=True)

    def get_absolute_url(self):
        return reverse(u'category_detail', kwargs={u'slug': self.slug})

    def __unicode__(self):
        return self.name


class New(models.Model):
    class Meta:
        verbose_name_plural = u'Жаңылыктар'
        verbose_name = u'Жаңылык'
        ordering = [u'-id']

    category = models.ForeignKey(Category, verbose_name=u'Категория',
                                 default=1, on_delete=models.CASCADE,
                                 blank=True, null=True)
    language = models.ForeignKey(Language, verbose_name=u'Тили', on_delete=models.CASCADE)
    name = models.CharField(verbose_name=u'Макаланын аталышы', db_index=True, max_length=255)
    slug = models.CharField(verbose_name=u'Транслит', max_length=200, blank=True)
    image = models.ImageField(verbose_name=u'Сүрөт', upload_to=u'news/', blank=True, null=True)
    text = RichTextUploadingField(verbose_name=u'Маалымат')
    likes = models.PositiveIntegerField(default=0)
    dislikes = models.PositiveIntegerField(default=0)
    user_rection = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True)
    created = models.DateTimeField(verbose_name=u'Дата', default=timezone.now)
    author = models.CharField(verbose_name=u'Макаланын автору', blank=True, null=True, max_length=200)
    start_time = models.DateTimeField(verbose_name=u'Начало', blank=True, null=True)
    end_time = models.DateTimeField(verbose_name=u'Конец', blank=True, null=True)
    organizator = models.CharField(verbose_name=u'Организатор', max_length=150, blank=True, null=True)
    mesto = models.CharField(verbose_name=u'Место проведения', max_length=150, blank=True, null=True)
    protsent = models.IntegerField(verbose_name=u'Процент проекта', blank=True, null=True)
    is_public = models.BooleanField(default=True)

    def get_absolute_url(self):
        return reverse(u'ru_article_detail', kwargs={u'slug': self.slug})

    def image_tag(self):
        return mark_safe('<img src="%s" width="150" height="150" />' % (self.image.url))

    image_tag.short_description = u'Сүрөт'

    def delete(self, *args, **kwargs):
        self.image.delete(save=False)
        super(New, self).delete(*args, **kwargs)

    def __unicode__(self):
        return self.name


class GlavSlider(models.Model):
    class Meta:
        verbose_name_plural = u'Слайдер'
        verbose_name = u'Слайдер'
        ordering = ['-id']

    language = models.ForeignKey(Language, verbose_name=u'Тили', on_delete=models.CASCADE)
    name = models.CharField(verbose_name=u'Аты', max_length=200)
    text = models.TextField(verbose_name=u'Маалымат')
    image = models.ImageField(verbose_name=u'Фото для слайдера', upload_to=u'slider/')

    def __unicode__(self):
        return self.name

    def image_tag(self):
        return mark_safe('<img src="%s" width="150" height="150" />' % (self.image.url))

    image_tag.short_description = u'Сүрөт'


class OFonde(models.Model):
    class Meta:
        verbose_name_plural = u'Ассоциация жөнүндө'
        verbose_name = u'Ассоциация жөнүндө'
        ordering = ['-id']

    language = models.ForeignKey(Language, verbose_name=u'Тили', on_delete=models.CASCADE)
    adres = models.CharField(verbose_name=u'Дарек', max_length=200, db_index=True)
    phone = models.CharField(verbose_name=u'Телефон', max_length=150, db_index=True)
    email = models.EmailField(verbose_name=u'Емейл')
    karta = models.CharField(verbose_name=u'Карта', max_length=400)
    facebook = models.CharField(verbose_name=u'Фейсбук', max_length=250, blank=True, null=True)
    instagram = models.CharField(verbose_name=u'Инстаграм', max_length=250, blank=True, null=True)
    youtube = models.CharField(verbose_name=u'Ютуб', max_length=250, blank=True, null=True)

    def __unicode__(self):
        return str(self.id)


class Fondjonundo(models.Model):
    class Meta:
        db_table = u'Ассоциация'
        verbose_name_plural = u'Ассоциациянын ачыктамасы'
        verbose_name = u'Ассоциациянын ачыктамасы'
        ordering = ['-id']

    language = models.ForeignKey(Language, verbose_name=u'Тили', on_delete=models.CASCADE)
    name = models.CharField(verbose_name=u'Аты', max_length=100)
    text = RichTextUploadingField(verbose_name=u'Багыттар', blank=True, null=True)

    def __unicode__(self):
        return self.name


class Chlen_Partner(models.Model):
    class Meta:
        verbose_name_plural = u'Члены и партнеры'
        verbose_name = u'Члены и партнеры'
        ordering = ['-id']

    category = models.ForeignKey(Category, verbose_name=u'Категория', default=1, on_delete=models.CASCADE)
    image = models.ImageField(verbose_name=u'Сүрөт', upload_to=u'chlleny/')

    def __unicode__(self):
        return str(self.id)

    def image_tag(self):
        return mark_safe('<img src="%s" width="150" height="150" />' % (self.image.url))

    image_tag.short_description = u'Сүрөт'


class GlavCategoryForKatalog(models.Model):
        class Meta:
            db_table = u'Главная категория для каталога'
            verbose_name_plural = u'Главные категории для каталога'
            verbose_name = u'Главная категория для каталога'
            ordering = ['-id']

        language = models.ForeignKey(Language, verbose_name=u'Тили', on_delete=models.CASCADE)
        name = models.CharField(verbose_name=u'Аты', max_length=150)
        slug = models.CharField(verbose_name=u'Транслит', max_length=200, blank=True)
        style = models.CharField(verbose_name=u'Добавить класс', max_length=200, blank=True, null=True)

        def __unicode__(self):
            return self.name


class CategoryForKatalog(models.Model):
        class Meta:
            db_table = u'Категория для каталога'
            verbose_name_plural = u'Категории для каталога'
            verbose_name = u'Категория для каталога'
            ordering = ['-id']

        language = models.ForeignKey(Language, verbose_name=u'Тили', on_delete=models.CASCADE)
        glavcategory = models.ForeignKey(GlavCategoryForKatalog, verbose_name=u'Главная категория для каталога',
                                         on_delete=models.CASCADE)
        name = models.CharField(verbose_name=u'Аты', max_length=150)
        slug = models.CharField(verbose_name=u'Транслит', max_length=200, blank=True)

        def __unicode__(self):
            return self.name


class PostForKatalog(models.Model):
    class Meta:
        db_table = u'Пост для каталога'
        verbose_name_plural = u'Посты для каталога'
        verbose_name = u'Пост для каталога'
        ordering = ['-id']

    language = models.ForeignKey(Language, verbose_name=u'Тили', on_delete=models.CASCADE)
    category = models.ForeignKey(CategoryForKatalog, verbose_name=u'Категория для поста',
                                     on_delete=models.CASCADE)
    name = models.CharField(verbose_name=u'Наименование организации', max_length=150)
    image = models.ImageField(upload_to=u'katalog/')
    address = models.CharField(verbose_name=u'Место нахождения', max_length=150)
    vid = models.CharField(verbose_name=u'Вид деятельности', max_length=150)
    rukovoditel = models.CharField(verbose_name=u'Руководитель', max_length=150)
    phone = models.CharField(verbose_name=u'Контакты', max_length=150)
    email = models.EmailField(verbose_name=u'Почта', max_length=150)
    site = models.CharField(verbose_name=u'Сайт', max_length=150, blank=True, null=True)
    slug = models.CharField(verbose_name=u'Транслит', max_length=200, blank=True)

    def __unicode__(self):
        return self.name

templates/ru/album_list.html
{% extends 'ru/base.html' %}
{% block title %}
    {{ h2|upper }}
{% endblock %}
{% block css %}
{% endblock %}
{% block content %}
    {% include 'generic/h2.html' %}
    <hr class="w3-border-amber">
    <div class="w3-container">
        <div class="w3-row-padding" style="background-color: #dddddd">
            {% for album in albums %}
                <div class="w3-quarter w3-margin-top">
                    <div class="w3-container w3-card-4 w3-white w3-left-align w3-margin-bottom "
                         style="height: 320px; padding: 8px;">
                        <div class="test"
                             style="position: relative;overflow:hidden;background-image: url({{ album.oblojka.url }});
                                     background-position: center;
                                     height: 220px;
                                     background-size: cover;">
                        </div>
                        <div class="w3-container">
                                <b title="{{ album.ru_name }}"><a href="{{ album.ru_get_absolute_url }}"
                                      class="w3-hover-text-green">{{ album.ru_name|truncatechars:35 }}</a></b>
                                <hr class="hr" style="margin-top: 2%">
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        {% include 'generic/paginator.html' %}
    </div>
{% endblock %}

templates/ru/anonsy.html
{% extends 'ru/base.html' %}
{% block css %}
{% endblock %}
{% block title %}
    {{ h2|upper }}
{% endblock %}
{% block js %}
{% endblock %}
{% block content %}{% load staticfiles %}
    <div style="position: relative">
        {% include 'generic/h2.html' %}
        <!--NOVOSTI-->
        <div class="novosti">
            <div class="nov-content ">
                <div class="w3-row-padding w3-margin-top w3-center"
                     style="position:relative;box-sizing: border-box; content: '';">
                    {% for cat in category %}

                        <div class="w3-third ">
                            <div class="w3-card-4 w3-margin white">

                                <div class="test"
                                     style="position: relative;overflow:hidden;background-image: url({{ cat.image.url }});
                                             min-height: 300px;
                                             background-position: center;
                                             background-size: cover;">

                                </div>
                                <div class="w3-margin novosti-content">
                                    <a href="{% url 'ru_anonsy_detail' slug=cat.slug %}" title="{{ cat.name }}">
                                        <h3 class="w3-hover-text-green w3-left-align">
                                            <b>{{ cat.name|truncatechars:35 }}</b>
                                        </h3></a>
                                    <hr class="hr">
                                    <div class="w3-left">
                                        <i class="fa fa-clock-o w3-text-green w3-margin">
                                            <span class="w3-text-black">{{ cat.created|time }}</span>
                                        </i>
                                        <i class="w3-text-green fa fa-calendar w3-margin">
                                            <span class="w3-text-black">{{ cat.created|date:'y.m.d' }}</span>
                                        </i>
                                    </div>
                                    <br><br>
                                    <div class="w3-padding w3-left-align">
                                            {{ cat.text|truncatechars:70 }}
                                        <br>
                                    </div>
                                </div>
                            </div>
                        </div>

                    {% endfor %}

                </div>
            </div>
            {% include 'generic/paginator.html' %}
        </div>

    </div>



    <style>
        .top-zagolov {
            padding-top: 200px;
            padding-left: 150px;
            padding-right: 150px;
            font-size: 8vw;
        }
    </style>
{% endblock %}

templates/ru/anonsy_detail.html
{% extends 'ru/base.html' %}
{% block css %}
{% endblock %}
{% block title %}
    {{ h2|upper }}
{% endblock %}

{% block content %}
    {% include 'generic/h2.html' %}
    <div class="novosti w3-row w3-light-gray" style="background-color: #a5a5a5;background-size: 100vh 100vh;">
        <div class="w3-col l8 s12">
            <!-- Blog entry -->
            <div class="w3-card-4 w3-margin w3-white">
                <img src="{{ article.image.url }}" alt="Nature" style="width:100%">
                    <div class="w3-row">
                        <div class="w3-half w3-padding-large">
                            <div><b>Начало мероприятия</b></div>
                            <i class="fa fa-clock-o w3-text-green w3-margin">
                                <span class="w3-text-grey">{{ article.start_time|time }}</span>
                            </i>
                            <i class="w3-text-green fa fa-calendar w3-margin">
                                <span class="w3-text-grey">{{ article.start_time|date:'y.m.d' }}</span>
                            </i>
                        </div>
                        <div class="w3-half w3-padding-large">
                            <div><b>Конец мероприятия</b></div>
                            <i class="fa fa-clock-o w3-text-green w3-margin">
                                <span class="w3-text-grey">{{ article.end_time|time }}</span>
                            </i>
                            <i class="w3-text-green fa fa-calendar w3-margin">
                                <span class="w3-text-grey">{{ article.end_time|date:'y.m.d' }}</span>
                            </i>
                        </div>
                    </div>
                    <div class="w3-container" style="padding-left: 5%">
                        <i class="w3-text-green fa fa-user-secret ">
                            <span class="w3-text-black">Организатор: </span>
                            <span class="w3-text-grey">{{ article.organizator }}</span>
                        </i>
                    </div>


                    <div class="w3-container" style="padding-left: 5%">
                        <i class="w3-text-green fa fa-location-arrow ">
                            <span class="w3-text-black">Место проведение: </span>
                            <span class="w3-text-grey">{{ article.mesto }}</span>
                        </i>
                    </div>

                <br>
                <hr class="hr">

                <div class="w3-container">
                    <p>{{ article.text }}</p>
                    <br><br><br>

                </div>

                <hr class="w3-border-green">
                <div class="w3-container w3-margin w3-right">
                    {#                <div class="sharethis-inline-share-buttons"></div>#}
                    <!-- Go to www.addthis.com/dashboard to customize your tools -->
                    <div class="addthis_inline_share_toolbox"></div>
                </div>
            </div>
        </div>

        <!-- Introduction menu -->
        <div class="w3-col l4">
            <!-- About Card -->
            <div class="w3-card w3-margin">
                <div class="w3-green w3-text-white w3-container w3-padding">
                    <h4 class=""><b>Наши проекты</b></h4>
                </div>
                <ul class="w3-ul w3-hoverable w3-white">
                    {% for article in projects %}
                        <li class="w3-padding-16 w3-hover-black">
                            <img src="{{ article.image.url }}" alt="Image" class="w3-left w3-margin-right"
                                 style="width:50px">
                            <a href="{{ article.get_absolute_url }}" class="w3-large"
                               title="{{ article.name }}">{{ article.name|truncatechars:30 }}</a><br>
                        </li>

                    {% endfor %}


                </ul>
            </div>
            <hr class="hr w3-margin">

            <!-- Posts -->
            <div class="w3-card w3-margin">
                <div class="w3-green w3-text-white w3-container w3-padding">
                    <h4 class=""><b>Последние новости</b></h4>
                </div>
                <ul class="w3-ul w3-hoverable w3-white">
                    {% for article in articles %}
                        <li class="w3-padding-16 w3-hover-black">
                            <img src="{{ article.image.url }}" alt="Image" class="w3-left w3-margin-right"
                                 style="width:50px">
                            <a href="{{ article.get_absolute_url }}" class="w3-large"
                               title="{{ article.name }}">{{ article.name|truncatechars:30 }}</a><br>
                        </li>

                    {% endfor %}


                </ul>
            </div>
            <hr>

            <hr>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5d3c3f457db0da35"></script>
{% endblock %}

templates/ru/chlenstvo.html
{% extends 'ru/base.html' %}
{% block css %}
{% endblock %}
{% block title %}
    {{ h2|upper }}
{% endblock %}
{% block js %}
{% endblock %}
{% block content %}
    {% include 'generic/h2.html' %}
    <br><br><br>
    <div class="ss w3-margin w3-center">
        <h3>
            <b>Почему выгодно и важно стать приверженцем принципов и ценностей <span class="w3-text-green">МАПЭФ и вступить в
                членство?</span></b>
        </h3>

        <p>Присоединяясь к сообществу прогрессивных предпринимателей Кыргызстана через участие в деятельности ассоциации
            МАПЭФ, бизнесмены получают возможность защиты и продвижения своих интересов на государственном и локальном
            уровнях, доступа к обширным контактам и связям в деловой среде. Гибкая политика в деятельности ассоциации
            построена с учетом гендерных аспектов и нацелена на восприятие самых передовых мировых процессов ведения
            бизнеса. Членство в МАПЭФ позволяет содействовать успешному развитию бизнес-среды в Кыргызстане для выработки
            собственных национальных стандартов ведения бизнеса.</p>
    <hr class="hr w3-margin">

    </div><br><br><br>
    <div class="w3-row-padding w3-margin">
        <div class="w3-half">
            <div class="w3-margin">
                <h2 class="w3-center w3-margin w3-text-green"><b>Как вступить в <span class="w3-text-black">МАПЭФ?</span></b></h2>
                <p class="w3-margin">
                    <p>Для вступления в ассоциацию необходимо сделать 2 простых шага:</p>
                <br>
                    <p>1) заполнить форму, с указанием: ФИО, номера телефона, адреса электронной почты;</p><br>

                    <p>2) отправить заполненную форму. Наши сотрудники обязательно свяжется с вами в
                    течении одного часа</p><br>
                </p>
            </div>
        </div>

        <div class="w3-half">
            <div class="w3-margin">
                <div class="w3-card-4">
                    <div class="w3-container w3-green">
                        <h2 class="w3-center">Контактные данные</h2>
                    </div>

                    <form class="w3-container w3-margin" action="{% url 'ru_contact_form' %}" method="post">{% csrf_token %}
                        <p>
                            <input class="w3-input" type="text" name="name" required>
                            <label>Ваше имя</label></p>
                        <p>
                            <input class="w3-input" type="text" name="phone" required>
                            <label>Телефонный номер</label>
                        </p>
                        <p>
                            <input class="w3-input" type="text" name="email" required>
                            <label>Электронная почта</label>
                        </p>
                        <input type="submit" class="w3-green w3-button w3-margin-top w3-margin-bottom w3-right w3-hover-black w3-round" >
                    </form>
                </div>
            </div>
        </div>
    </div>
    <br><br><br>

    <style>
        .top-zagolov {
            font-size: 6vw;
        }
    </style>
{% endblock %}

templates/ru/image_list.html
{% extends 'ru/base.html' %}
{% load staticfiles %}
{% block title %}
    {{ h2|upper }}
{% endblock %}
{% block css %}

    <link rel="stylesheet" href="{% static 'css/jquery.galereya.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.galereya.ie.css' %}">
    <link rel="stylesheet" href="{% static 'css/galereya.css' %}">
{% endblock %}
{% block content %}
    {% include 'generic/h2.html' %}

    {% include 'generic/paginator.html' %}

    <style>
        .gallery-content {
            width: 100%;
            min-height: 100vh;
            height: auto;
            position: relative;
            overflow: auto;

        }
    </style>
    <div class="gallery-content">
        <div class="w3-container" style="width: 100%;height: 100%;position: absolute;content: '';">
            <div id="gal1">
                {% for album in page_obj %}


                    <img src="{{ album.image.url }}" data-desc="{% if album.ru_description %}
                            <p>{{ album.ru_description }}</p>
                        {% endif %}" data-fullsrc="{{ album.image.url }}" alt="">
                {% endfor %}
                <br><br><br>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <script src="{% static 'js/jquery.galereya.min.js' %}"></script>
    <script>
        $('#gal1').galereya({
            wave: false,
            modifier: 'ex1',
            spacing: 10,
        });

    </script>
{% endblock %}

templates/ru/index.html
{% extends 'ru/base.html' %}
{% block content %}
    {% include 'ru/generic/glavnyi_slider.html' %}
    {% include 'ru/generic/opisanie_mapef.html' %}
    {% include 'ru/generic/novosti_mapef.html' %}
    {% include 'ru/generic/dostijenie_mapef.html' %}
    {% include 'ru/generic/project_mapef.html' %}
{% endblock %}

templates/ru/katolog.html
{% extends 'ru/base.html' %} {% load category %}
{% block css %}
{% endblock %}
{% block title %}
    {{ h2|upper }}
{% endblock %}
{% block js %}
{% endblock %}
{% block content %}
    {% include 'generic/h2.html' %}
    <br><br><br>
    <div class="w3-containner sss">
        <div class="w3-row-padding">
            {% for glav in glavnyi %}

                <div class="w3-half w3-margin-top">
                    <a href="{% url 'ru_katalog_detail' slug=glav.slug %}">
                        <h3 class="w3-hover-text-black glav-katalog w3-text-green"><i
                                class="{{ glav.style }}"></i> {{ glav }}</h3>
                    </a>
                    <hr class="hr">


                    <p>
                        {% for podglav in glav.slug|category_set %}
                            <a href="{% url 'ru_katalog_detail' slug=podglav.slug %}"
                               class="w3-padding-16 w3-hover-text-green">{{ podglav }}, </a>

                        {% endfor %}
                    </p>
                </div>
            {% endfor %}

        </div>
    </div>

    <style>
        .sss {
            padding-left: 10%;
            padding-right: 10%;
        }

        .glav-katalog {
            font-size: 2.5vw;
        }

        .top-zagolov {
            font-size: 5vw;
        }

        @media screen and (max-width: 480px) {
            .glav-katalog {
                font-size: 7vw;
            }
        }

        @media screen and (max-width: 780px) {
            .glav-katalog {
                font-size: 3vw;
            }
        }

    </style>
    <br><br><br>
{% endblock %}

templates/ru/katolog_detail.html
{% extends 'ru/base.html' %} {% load category %}
{% block css %}
{% endblock %}
{% block title %}
    {{ h2|upper }}
{% endblock %}
{% block js %}
{% endblock %}
{% block content %}
    {% include 'generic/h2.html' %}
    <br><br><br>
    <div class="w3-containner sss">
        <div class="w3-row-padding">
            {% for glav in page_obj %}
                <ul class="w3-ul w3-card-4">
                    <li class="w3-bar">
                        <img src="{{ glav.image.url }}" class="w3-bar-item image">
                        <h4 class="w3-text-green w3-bar-item h4-text">
                            Организация: <span>{{ glav.name }}</span><br>
                            Адрес: <span>{{ glav.address }}</span><br>
                            Вид деятельности: <span>{{ glav.vid }}</span><br>
                            Руководитель: <span>{{ glav.rukovoditel }}</span><br>
                            Контакты: <span>{{ glav.phone }}</span><br>
                            E-mail: <span>{{ glav.email }}</span><br>
                        </h4>
                    </li>
                </ul>


                <hr class="hr">

            {% endfor %}

        </div>
        {% include 'generic/paginator.html' %}
    </div>


    <style>
        .sss {
            padding-left: 10%;
            padding-right: 10%;
        }

        .glav-katalog {
            font-size: 2.5vw;
        }

        .top-zagolov {
            font-size: 5vw;
        }

        h4 span {
            color: #000;
        }

        .image {
            width: 30% !important;
        }

        @media screen and (max-width: 480px) {
            .glav-katalog {
                font-size: 7vw;
            }

            .image {
                width: 100% !important;
            }

            .h4-text {
                font-size: small;
            }
        }

        @media screen and (max-width: 780px) {
            .glav-katalog {
                font-size: 3vw;
            }
        }

    </style>
    <br><br><br>
{% endblock %}

templates/ru/onas.html
{% extends 'ru/base.html' %}
{% block css %}
{% endblock %}
{% block title %}
    {{ h2|upper }}
{% endblock %}
{% block js %}
{% endblock %}
{% block content %}
    {% include 'generic/h2.html' %}
    <div class="w3-row-padding w3-light-gray">

        <div class="w3-third " style="">
            <div class="w3-bar-block w3-white w3-padding-large">
                {% for foo in fond %}
                    <button id="Fade1" class="w3-bar-item w3-button w3-mobile tablink w3-padding-large"
                            onclick="openLink(event, '{{ foo.name }}')">
                        <b>{{ foo.name }}</b>
                    </button>
                {% endfor %}

            </div>
        </div>

        <div class="w3-twothird ">
            <div class="w3-white w3-padding-large">
                {% for foo in fond %}
                    <div id="{{ foo.name }}" class="w3-padding-large city w3-animate-zoom" style="display:none">
                        <h2>{{ foo.name }}</h2>
                        <hr class="hr">
                        <p>{{ foo.text }}</p>
                    </div>
                {% endfor %}

            </div>
        </div>

        <script>
            function openLink(evt, animName) {
                var i, x, tablinks;
                x = document.getElementsByClassName("city");
                for (i = 0; i < x.length; i++) {
                    x[i].style.display = "none";
                }
                tablinks = document.getElementsByClassName("tablink");
                for (i = 0; i < x.length; i++) {
                    tablinks[i].className = tablinks[i].className.replace(" w3-green", "");
                }
                document.getElementById(animName).style.display = "block";
                evt.currentTarget.className += " w3-green";
            }

            document.getElementById("Fade1").click();
        </script>
    </div>

    <style>
        .top-zagolov {
            font-size: 6vw;
        }
    </style>
{% endblock %}